name: CI

on:
  push:
    branches:
      - master

jobs: 
    build:
      name: 'Build and Push'
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [22]

      steps:
      - name: Checkout code | ${{matrix.node}}
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node}}
          cache: 'yarn'
      
      - run: yarn
      - run: yarn run test

      - name: Build docker image
        run: docker build -t rocket-ci-api:lastest .



#docker tag local-image:tagname new-repo:tagname
#docker push new-repo:tagname